FROM python:3.5-slim

SHELL ["/bin/bash", "-c"]

RUN apt-get update -qq && \
  apt-get install -y --no-install-recommends \
  build-essential \
  wget \
  openssh-client \
  graphviz-dev \
  pkg-config \
  git-core \
  openssl \
  libssl-dev \
  libffi6 \
  libffi-dev \
  libpng-dev \
  curl && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
  mkdir /app

WORKDIR /app
#
# RUN apt-get update && \
#	apt-get install -y openssh-client git gcc&& \
#	rm -rf /var/lib/apt/lists/*
COPY ./core/requirements.txt .
RUN pip install -r /app/requirements.txt --no-cache-dir
COPY ./core .
VOLUME ["/app/model", "/app/config", "/app/project"]
EXPOSE 5005
RUN chmod +x ./entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]
CMD ["start", "-d", "./model"]