FROM python:3.6-slim
SHELL ["/bin/bash", "-c"]
# Run updates, install basics and cleanup
# - build-essential: Compile specific dependencies
# - git-core: Checkout git repos
RUN apt-get update -qq \
    && apt-get install -y --no-install-recommends build-essential git-core \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


RUN mkdir /app
WORKDIR /app
COPY ./nlu/requirements.txt .
RUN pip install -r /app/requirements.txt --no-cache-dir
COPY ./nlu .

RUN python -m spacy download fr_core_news_sm \
    && python -m spacy link fr_core_news_sm fr
RUN chmod +x ./entrypoint.sh
VOLUME ["/app/projects", "/app/logs", "/app/data"]

EXPOSE 5000

ENTRYPOINT ["./entrypoint.sh"]
CMD ["start", "--path", "/app/projects"]

